<?php 
	if (defined('RUNNING_FROM_ROOT')) {
        $this->plugin('basePath')->setBasePath($this->basePath().'/public');
    }    

?>

<script>
    
    function selectInCombo(combo,val)
    {
        for(var indice=0 ;indice<document.getElementById(combo).length;indice++)
        {
            if (document.getElementById(combo).options[indice].value==val ){
                document.getElementById(combo).selectedIndex =indice;
            }
        }
    }

</script>

<?php
    $flash=$this->flashMessenger()
            ->setMessageOpenFormat('<div%s id="alertaMSJ"><strong>')
            ->setMessageSeparatorString('')
            ->setMessageCloseString('</strong></div>');
?>


<?php echo $flash->render('msjError',array('alert', 'alert-danger', 'alertaMSJ'));?>
<?php echo $flash->render('msjExito',array('alert', 'alert-success', 'alertaMSJ'));?>


<!--Page Title-->
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<div id="page-title">
    <h1 class="page-header text-overflow">LOCUTOR</h1>
</div>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<!--End page title-->

<!--Breadcrumb-->
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<ol class="breadcrumb">
    <li></li>
</ol>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<!--End breadcrumb-->


<?php $date_dia=date('d-m-Y') ?>
<!--Page content-->
<!--===================================================-->
<div id="page-content">

    <div class="row">
        <div class="col-sm-12 col-lg-4">
    
            <!--Registered User-->
            <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
            <div class="panel media pad-all">
                <div class="media-left">
                    <span class="icon-wrap icon-wrap-sm icon-circle bg-info">
                    <i class="fa fa-comment-o fa-2x"></i>
                    </span>
                </div>
    
                <div class="media-body">
                    <p class="text-2x mar-no text-thin js-total_menciones"><?php echo (int)$t_menciones_dia ?></p>
                    <p class="text-muted mar-no">Menciones del día [<?php echo $date_dia ?>]</p>
                </div>
            </div>
            <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
    
        </div>
        <div class="col-sm-12 col-lg-4">
    
            <!--New Order-->
            <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
            <div class="panel media pad-all">
                <div class="media-left">
                    <span class="icon-wrap icon-wrap-sm icon-circle bg-success">
                    <i class="fa fa-comment-o fa-2x"></i>
                    </span>
                </div>
    
                <div class="media-body">
                    <p class="text-2x mar-no text-thin js-mencion_leidas"><?php echo $t_leidas_dia; ?></p>
                    <p class="text-muted mar-no">Leidas [<?php echo $date_dia ?>]</p>
                </div>
            </div>
            <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
    
        </div>
        <div class="col-sm-12 col-lg-4">
    
            <!--Comments-->
            <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
            <div class="panel media pad-all">
                <div class="media-left">
                    <span class="icon-wrap icon-wrap-sm icon-circle bg-danger">
                    <i class="fa fa-comment fa-2x"></i>
                    </span>
                </div>
    
                <div class="media-body">
                    <p class="text-2x mar-no text-thin js-mencions_no_leidas"><?php echo $t_no_leidas_dia; ?></p>
                    <p class="text-muted mar-no">Sin leer [<?php echo $date_dia ?>]</p>
                </div>
            </div>
            <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
    
        </div>
    </div>

    
    <div class="tab-base">
                    
    <!--Nav tabs-->
    <ul class="nav nav-tabs tabs-right">

        <li class="active">
            <a data-toggle="tab" href="#tab-menciones">
                <i class="fa fa-commenting-o"></i> MENCIONES</span>
            </a>
        </li>

        <li class="">
            <a data-toggle="tab" href="#tab-agenda">
                <i class="fa fa-calendar"></i> AGENDA
            </a>
        </li>
    </ul>

    <!--Tabs Content-->
    <div class="tab-content">
        
        <div id="tab-menciones" class="tab-pane fade active in">
            
            <div class="form-inline">
                <div class="row">
                    <div class="col-sm-4 table-toolbar-left">
                        <button id="demo-btn-addrow" class="btn btn-default btn-rounded js-change-date-minus" data-date="00-00-0000"><i class="fa fa-arrow-left"></i> <span>00-00-0000</span></button>
                    </div>
                    <div class="col-sm-4 text-center">
                        <h4 class="text-muted text-info">Menciones del día <span class='js-day'><?php echo $date_dia ?></span></h4>
                    </div>
                    <div class="col-sm-4 table-toolbar-right">
                        <button id="demo-btn-addrow" class="btn btn-default btn-rounded js-change-date-plus" data-date="00-00-0000" ><span>00-00-0000</span> <i class="fa fa-arrow-right"></i></button>
                    </div>
                </div>
            </div>

            <div class="table-responsive mar-top">
                <table class="table table-striped table-bordered" id="tablaMenciones"  cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th style="width:400px;">EXTRACTO</th>
                            <th>LEIDO</th>
                            <th>HORA</th>
                            <th>ACCIÓN</th>
                        </tr>
                    </thead>
                    <tbody>
                        
                    </tbody>
                </table>
            </div>
        </div>

        <div id="tab-agenda" class="tab-pane fade">
            
            <div class="mar-btm">
                <h4 class="text-thin text-semibold">Simbologia</h4>
                <span class="label mar-top mar-btm" style="background-color:#c3cedb;">Mención Expirada</span>
            </div>

            <!-- Calendar placeholder-->
            <!-- ============================================ -->
            <div id='calendario-menciones'></div>
            <!-- ============================================ -->

        </div>

    </div>

</div>

</div>
<!--===================================================-->
<!--End page content-->


<?php 
    echo $this->inlineScript()->prependFile($this->basePath('js/jquery.magnific-popup.min.js'))
                                ->prependFile($this->basePath('plugins/jquery-validation/additional-methods.min.js'))
                                ->prependFile($this->basePath('plugins/jquery-validation/jquery.validate.min.js'))

                                ->prependFile($this->basePath('plugins/dropzone/dropzone.min.js'))
                                ->prependFile($this->basePath('plugins/bootstrap-timepicker/bootstrap-timepicker.min.js'))
                                ->prependFile($this->basePath('plugins/bootstrap-datepicker/bootstrap-datepicker.js'))

                                ->prependFile($this->basePath('plugins/fullcalendar/fullcalendar.min.js'))
                                ->prependFile($this->basePath('plugins/fullcalendar/lib/jquery-ui.custom.min.js'))
                                ->prependFile($this->basePath('plugins/fullcalendar/lib/moment.min.js'))


                                ->prependFile($this->basePath('/plugins/bootstrap-select/ajax-bootstrap-select.min.js'))
                                ->prependFile($this->basePath('/plugins/bootstrap-select/bootstrap-select.min.js'));
?>

<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/magnific-popup.css">

<!-- SELECT BOOTSTRAP -->
<link rel="stylesheet" href="<?php echo $this->basePath()?>/plugins/bootstrap-select/bootstrap-select.min.css">
<link rel="stylesheet" href="<?php echo $this->basePath()?>/plugins/bootstrap-select/ajax-bootstrap-select.min.css">

<!--Dropzone [ OPTIONAL ]-->
<link href="<?php echo $this->basePath(); ?>/plugins/dropzone/dropzone.css" rel="stylesheet">

<!--Bootstrap Timepicker [ OPTIONAL ]-->
<link href="<?php echo $this->basePath(); ?>/plugins/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet">

<!--Bootstrap Datepicker [ OPTIONAL ]-->
<link href="<?php echo $this->basePath(); ?>/plugins/bootstrap-datepicker/bootstrap-datepicker.css" rel="stylesheet">

<!--Full Calendar [ OPTIONAL ]-->
<link href="<?php echo $this->basePath(); ?>/plugins/fullcalendar/fullcalendar.css" rel="stylesheet">

<script type="text/javascript">
    
    // *****************************************************
    //URL MENCIONES
    var urlGetDataMencion               = '<?php echo $this->url("menciones/mencionesGetData"); ?>';
    var urlStatusReadMencion            = '<?php echo $this->url("menciones/mencionesStatusRead"); ?>';
    var urlTablaLocutor                 = '<?php echo $this->url("locutor/locutorTabla"); ?>';
    var urlCalendarioMencion            ='<?php echo $this->url("menciones/mencionesCalendario"); ?>';
    var global_isLoadTablaLocutor       = false;
    var global_isLoadCalendarioMencion  = false;


    var global_noImage='<?php echo $this->basePath()."/img/".$this->NoImage; ?>';

    function clearClassRow(tabla_name){
        $("#"+tabla_name+" tr").removeClass("danger");
        $("#"+tabla_name+" tr").removeClass("info");
        $("#"+tabla_name+" tr").removeClass("success");
    }

    // +++++++++++++++++++++++++++++++++++++++++++++++
    // LIMPIA EL FORMULARIO
    function clearForm()
    {
        document.getElementById("saveMencion").reset();
        $("#mencionHidden").val("0");
        $(".imgCargando").empty();
    }

    function sumarDias(fecha, dias){
        fecha.setDate(fecha.getDate() + dias);
        return fecha;
    }

    function loadDataTablaMenciones(dia){
        
        if( global_isLoadTablaLocutor==true ){
            $('#tablaMenciones').DataTable().destroy();
        }

        $('#tablaMenciones').DataTable({
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": urlTablaLocutor,
            "columns": [
                { "data": "extracto" },
                { "data": "estado" },
                { "data": "hora" },
                { "data": "version" }
            ],
            // "columnDefs": [ 
            //     { 
            //         "targets": 3, 
            //         "orderable": false 
            //     } 
            // ],
            "ordering": false,
            "bLengthChange": false,
            "searching": false,
            "order": [ 2, "ASC" ],
            responsive: true,
            "iDisplayLength": 100,
            "dom": 'T<"clear">lfrtip',
            "tableTools": {
                "sSwfPath": "<?php echo $this->basePath()?>/js/plugins/dataTables/swf/copy_csv_xls_pdf.swf"
            },
            "fnServerParams": function (aoData) { 
                aoData.push({ "name": 'dia', "value": dia });
            },
            "oLanguage": {
                "sProcessing":     "Procesando...",
                "sLengthMenu":     "Mostrar _MENU_ registros",
                "sZeroRecords":    "No se encontraron resultados",
                "sEmptyTable":     "Ningún dato disponible en esta tabla",
                "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix":    "",
                "sSearch":         "Buscar:",
                "sUrl":            "",
                "sInfoThousands":  ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst":    "Primero",
                    "sLast":     "Último",
                    "sNext":     "Siguiente",
                    "sPrevious": "Anterior",
                },
                "fnInfoCallback": null,
            },
            "fnDrawCallback": function( oSettings ) {
                // -------------------------------------------------
                // TOOLTIP DE LOS BOTONES
                $('#tablaMenciones [data-toggle="tooltip"]').tooltip({ html:true });

                $("#tablaMenciones img.lazy").lazyload({
                    effect: "fadeIn"
                });
                $('.js-change-date-minus').prop('disabled', false);
                $('.js-change-date-plus').prop('disabled', false);
            }
        });
        
    }

    function plusMinusDate(type, dia, format){
        if(type=='plus'){
            dia=moment( dia, "DD-MM-YYYY").add(1, 'days').format(format);
        }
        else if(type=='minus'){
            dia=moment( dia, "DD-MM-YYYY").add(-1, 'days').format(format);
        }
        return dia;
    }

    function updateChangeDate(dia){
        var plus_day_show    =plusMinusDate('plus', dia, 'DD-MM-YYYY');
        var plus_day_data    =plusMinusDate('plus', dia, 'YYYY-MM-DD');

        var minus_day_show   =plusMinusDate('minus', dia, 'DD-MM-YYYY');
        var minus_day_data   =plusMinusDate('minus', dia, 'YYYY-MM-DD');

        $('.js-change-date-minus').data('date', minus_day_data);
        $('.js-change-date-minus span').text(minus_day_show);

        $('.js-change-date-plus').data('date', plus_day_data);
        $('.js-change-date-plus span').text(plus_day_show);

    }

    $(document).ready(function(){

        var source   = $("#alert-template").html();
        var template = Handlebars.compile(source);
        var sourceCarg   = $("#imgCargando-template").html();
        var templateCarg = Handlebars.compile(sourceCarg);

        //INICIALIZAMOS TOOLTIP
        $('[data-toggle="tooltip"]').tooltip({ html:true });


        $('.alertaMSJ').delay(2500).slideToggle(2500);

        // var d = moment( $(".js-day").text(), "DD-MM-YYYY")._d;
        // console.log(sumarDias(d, -1));
        // console.log(moment( $(".js-day").text(), "DD-MM-YYYY").add(-1, 'days')._d );
        // console.log(moment( $(".js-day").text(), "DD-MM-YYYY").add(1, 'days')._d );
        updateChangeDate( $(".js-day").text() );

        //=========================================================
        loadDataTablaMenciones( moment( $(".js-day").text(), "DD-MM-YYYY").format('YYYY-MM-DD') );
        global_isLoadTablaLocutor=true;
        //=========================================================

        //========================================================================
        //deshabilita - habilita
        $(document).on('click', '.linkLeida, .btnMarkRead',function () {
            var id=$(this).data('hora');
            var $this=$(this);
            $this.parents('tr').addClass("success");

            text="Estas seguro de marcar como leída esta mención?";
            confirmButtonText="Si, marcar";
            confirmButtonColor="#1ab394";
            title='¿Marcar?';
            titleExito="Mención marcada!";
            var fecha_now=moment( $(".js-day").text(), "DD-MM-YYYY").format('YYYY-MM-DD');
            
            swal({
                title: title,
                text: text,
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: confirmButtonColor,
                confirmButtonText: confirmButtonText,
                cancelButtonText: "Cancelar",
                closeOnConfirm: false,
                showLoaderOnConfirm: true,
            }, function (isConfirm) {
                if (isConfirm) {
                    $.post( urlStatusReadMencion, { horario: id, dia: fecha_now }, function( data ) {
                        if (data.status=="ok") {

                            if(typeof data.contadores.t_menciones_dia!='undefined'){
                                $(".js-total_menciones").text(data.contadores.t_menciones_dia);
                            }
                            if(typeof data.contadores.t_leidas_dia!='undefined'){
                                $(".js-mencion_leidas").text(data.contadores.t_leidas_dia);
                            }
                            if(typeof data.contadores.t_no_leidas_dia!='undefined'){
                                $(".js-mencions_no_leidas").text(data.contadores.t_no_leidas_dia);
                            }

                            //*************************************************
                            //SI MARCAMOS COMO LEIDA LA MENCION DESDE EL MODAL
                            if($this.hasClass('btnMarkRead')){
                                $this.hide(1);
                            }
                            //*************************************************

                            swal(titleExito, data.msj, "success");
                            setTimeout(function(){
                                $('#tablaMenciones').DataTable().draw(false);
                            }, 700);
                            clearClassRow('tablaMenciones');
                        }
                        else{
                            swal("Error", data.msj, "error");
                        }
                        

                    }, "json").fail(function(){
                        console.log('Error en el server');
                        swal("Error", 'Error en el servidor (contacte a su administrador).', "error");
                    });
                }else{
                    clearClassRow('tablaMenciones');
                }
                
            });
        });


        //*****************************************************************
        //ZONA CALENDARIO
        //*****************************************************************

        /* initialize the calendar
        -----------------------------------------------------------------*/
        var date = new Date();
        var d = date.getDate();
        var m = date.getMonth();
        var y = date.getFullYear();

        $('#calendario-menciones').fullCalendar({
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            lang: 'es',
            editable: false,
            droppable: true, // this allows things to be dropped onto the calendar
            timeFormat: 'H:mm',
            setHours: 1,
            eventLimit: 7,
            eventSources: [
                {
                    url: urlCalendarioMencion,
                    type: 'GET',
                    data: function() { // a function that returns an object
                        //PARA ENVIAR VALORES DINAMICOS
                        return {
                            // campus:1,
                            // usuario: $("#user_calendar").val(),
                        };
                    },
                    beforeSend: function(){
                        // $global_btnFilter=$(".btnFilterCalendar").button('loading');
                    },
                    success: function(){
                        // console.log('calendario refrescado');
                        // $global_btnFilter.button('reset');
                    },
                    error: function() {
                        // alert('there was an error while fetching events!');
                        console.log('Error al cargar');
                    },
                }
            ] ,
            eventConstraint: {
                start: date,
                end: '3000-01-01' // hard coded goodness unfortunately
            },
            eventClick: function(event, element) {
                if(event.old=='false'){
                    if( $("#checkRemove").is(":checked") ){
                        // deleteReserva(event);
                    }
                    else{
                        var datos={
                            mencion : event.id
                        };
                        getDataView(datos);
                    }
                }
            },
            eventMouseover : function(data, event, view) {
                // var hourStart=moment(data.start._i).format('HH:mm');
                var hourStart ='';
                var start_f   = moment(data.start._i).format('DD-MM-YYYY');
                var end_f     = moment(data.end._i).format('DD-MM-YYYY');

                var content = 
                    '<h4>'+hourStart+data.title+'</h4>'+
                    '<p>['+ start_f +' - '+ end_f +']</p>'+
                    '<p>'+data.description +'<p>';

                $(this).attr('data-toggle', 'tooltip');
                $(this).attr('data-placement', 'top');
                $(this).tooltip({ 
                    html:true,
                    title:content 
                });
                $(this).tooltip('show');
            },
            eventMouseout: function( event, jsEvent, view){
                // console.log($(this) );
            },
        });
        
        //*********************************************************************
        //REDIBUJAMOS EL CALENDARIO O LA TABLA (SEGUN EL TAB SELECCIONADO)
        $(".nav-tabs li a").click(function(){
            if( $(this).attr('href')=='#tab-agenda' ){
                setTimeout(function(){
                    if( global_isLoadCalendarioMencion==false ){
                        $('#calendario-menciones').fullCalendar('render');
                        global_isLoadCalendarioMencion=true;
                    }
                    else{
                        $("#calendario-menciones").fullCalendar( 'refetchEvents' );
                    }
                },200);
            }
            else if( global_isLoadTablaLocutor==true ){
                $('#tablaMenciones').DataTable().draw(false);
            }
        });
        //*********************************************************************

        $('#tablaMenciones').on('click', '.linkView', function(e){
            e.preventDefault();
            var tr      = $(this).parents('tr');
            var tr_prev = tr.prev();
            if( typeof $(this).data('status')!='undefined' && $(this).data('status')=='' ){
                //***************************************************************
                // VERSION SENCILLA VALIDANDO LA FILA ANTERIOR SOLAMENTE
                // if( typeof tr_prev.find('.linkView').data('status')!='undefined' && tr_prev.find('.linkView').data('status')=='' ){
                //     // swal("Advertencia", 'Debes marcar como leída la mención anterior, para poder visualizar esta.', "warning");
                //     // return false;
                //     console.log('advertencia');
                // }
                //***************************************************************
                var show_advertencia=false;
                $.each( $('#tablaMenciones tbody tr'), function(i, item){
                    if( $(item).attr('id')==tr.attr('id') ){
                        return false;
                    }
                    if( typeof $(item).find('.linkView').data('status')!='undefined' && $(item).find('.linkView').data('status')=='' ){
                        show_advertencia=true;
                    }
                    // console.log( i, $(item).attr('id'), $(item).find('.linkView').data('status'), show_advertencia );
                });
                if(show_advertencia==true){
                    $('.js_menciones_no_leidas_alert').show();
                    // swal("Advertencia", 'Debes marcar como leída la mención anterior, para poder visualizar esta.', "warning");
                    // return false;
                    // console.log('advertencia');
                }
            }

            if( $(this).attr('data')!='' ){
                var hora      = '';
                var status    = '';
                var fecha_now = moment( $(".js-day").text(), "DD-MM-YYYY").format('YYYY-MM-DD');

                if(typeof $(this).data('hora')!='undefined' && $(this).data('hora')!='' ){
                    hora = $(this).data('hora');
                }
                if(typeof $(this).data('status')!='undefined' && $(this).data('status')=='leida' ){
                    status = $(this).data('status');
                }
                var datos={
                    mencion : $(this).attr('data'),
                    hora    : hora,
                    status  : status,
                    section : 'tabla_menciones',
                    dia     : fecha_now
                };
                getDataView(datos);
            }
        });


        $(document).on('click', '.js-change-date-plus, .js-change-date-minus', function(){

            var dia_actual      =$(this).find('span').text();
            var dia_actual_data =$(this).data('date');
            $('.js-day').text(dia_actual);
            updateChangeDate( dia_actual );

            //MOSTRAMOS CARGANDO EN AMBOS
            $('.js-change-date-minus').prop('disabled', true);
            $('.js-change-date-plus').prop('disabled', true);


            //CARGAMOS LA TABLA
            loadDataTablaMenciones( dia_actual_data );
        });

        $(document).on('click', '.linkPop', function(e){
            e.preventDefault();
            // var content= $(this).parent().find('.js-content-mencion').html();
            // $(this).popover({
            //     content: content,
            //     html: true,
            //     placement: 'top',
            //     trigger: 'manual',
            //     title: 'Mención'
            // }).popover('toggle');
        });
    });

</script>


<!-- MODAL MENCIONES -->
<div id="myModalMenciones" class="modal inmodal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content" >
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title"></h4>
            </div>

            <!-- ICON CARGANDO -->
            <div class="panel-alert">
                <div class="imgCargando" class="alert-wrap in"></div>
            </div>
            <!-- /.FIN ICON CARGANDO -->
            
            <form id="saveMencion" action="" method="POST" enctype="multipart/form-data">

                <div class="modal-body" >
                    
                    <div class="row">

                        <div class="col-lg-7">

                            <div class="row">
                                <div class="col-lg-12" >
                                    <label class="text-semibold">Ingrese el periodo</label>
                                    <div id="mention-range">
                                        <div class="input-daterange input-group" id="datepicker">
                                            <input type="text" class="form-control" name="mention_date_start" />
                                            <span class="input-group-addon">Entre</span>
                                            <input type="text" class="form-control" name="mention_date_end" />
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-12 pad-top">
                                    
                                    <?php for($i=1; $i<=7; $i++): ?>
                                        <?php $arr_dias=array('Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo') ?>
                                        
                                        <div class="checkbox">
                                            <label class="form-checkbox form-normal form-primary form-text mar-rgt">
                                                <input type="checkbox" class="js-mention_days" name="mention_days[]" value="<?php echo (int)$i ?>"> <?php echo $arr_dias[$i-1]; ?>
                                            </label>
                                        </div>
                                        
                                    <?php endfor; ?>
                                </div>
                            </div>

                            <div class="form-group mar-top">
                                <label for="mention_description" class="text-semibold">Mención *</label>
                                <textarea class="form-control" name="mention_description" id="mention_description" maxlength="60000" cols="30" rows="10" required></textarea>
                            </div>


                            <input type="hidden" value="0" id="mencionHidden" name="mencionHidden" />
                            <input type="hidden" value="<?php echo $campana['idcamp']; ?>" id="campanaHidden" name="campanaHidden" />
                            
                        </div>

                        <div class="col-lg-5">
                            <h4>Horarios</h4>
                            <button type="button" class="btn btn-sm btn-block btn-success btnAddCampos"><i class="fa fa-plus"></i> Agregar Hora</button>
                            <div class="mar-top nano" style="height:500px;">
                                <div class="nano-content div-content-extra-data">
                                    
                                </div>
                            </div>
                        </div>
                    
                    </div>

                </div>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal" >Cerrar</button>
                    <button 
                        class="btn btn-primary btn-sm btnSave" 
                        data-loading-text="<i class='fa fa-spinner fa-pulse fa-fw'></i> Guardando">
                        <i class="fa fa-floppy-o"></i> Guardar
                    </button>
                </div>
            </form>

        </div>
    </div>
</div>
