<?php 
	if (defined('RUNNING_FROM_ROOT')) {
        $this->plugin('basePath')->setBasePath($this->basePath().'/public');
    }    

?>

<script>
    
    function selectInCombo(combo,val)
    {
        for(var indice=0 ;indice<document.getElementById(combo).length;indice++)
        {
            if (document.getElementById(combo).options[indice].value==val ){
                document.getElementById(combo).selectedIndex =indice;
            }
        }
    }

</script>

<?php
    $flash=$this->flashMessenger()
            ->setMessageOpenFormat('<div%s id="alertaMSJ"><strong>')
            ->setMessageSeparatorString('')
            ->setMessageCloseString('</strong></div>');
?>


<?php echo $flash->render('msjError',array('alert', 'alert-danger', 'alertaMSJ'));?>
<?php echo $flash->render('msjExito',array('alert', 'alert-success', 'alertaMSJ'));?>


<!--Page Title-->
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<div id="page-title">
    <h1 class="page-header text-overflow">CLIENTES</h1>
</div>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<!--End page title-->

<!--Breadcrumb-->
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<ol class="breadcrumb">
    <li></li>
</ol>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<!--End breadcrumb-->



<!--Page content-->
<!--===================================================-->
<div id="page-content">

    <div class="panel">
        <div class="panel-heading">
            <div class="panel-control">
                <a class="btn btn-info btn-sm pull-right btn-labeled fa fa-plus mar-top" id="nuevoRegistro" href="javascript:void(0);">Nuevo</a>
                <!-- <a href="<?php //echo $this->url('clientes/clientesExportar'); ?>" target="_blank" class="btn btn-success btn-sm pull-right btn-labeled fa fa-download mar-top" id="importarExcel">Exportar Clientes</a> -->
            </div>
            <h3 class="panel-title">Listado</h3>
        </div>
        <div class="panel-body">
            
            <div class="table-responsive">
                <table class="table table-striped table-bordered" id="tablaClientes"  cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>CLIENTE</th>
                            <th>FECHA</th>
                            <th>ACCIÓN</th>
                        </tr>
                    </thead>
                    <tbody>
                        
                    </tbody>
                </table>
            </div>


        </div><!--// fin ibox-content-->
    </div><!--// fin ibox-->

</div>
<!--===================================================-->
<!--End page content-->


<?php 
    echo $this->inlineScript()->prependFile($this->basePath('js/jquery.magnific-popup.min.js'))
                                ->prependFile($this->basePath('plugins/jquery-validation/additional-methods.min.js'))
                                ->prependFile($this->basePath('plugins/jquery-validation/jquery.validate.min.js'))

                                ->prependFile($this->basePath('plugins/redactor/redactor_source.js'))
                                ->prependFile($this->basePath('plugins/redactor/redactor_imagemanager.js'))
                                ->prependFile($this->basePath('plugins/redactor/redactor_2016.min.js'))

                                ->prependFile($this->basePath('plugins/chosen/chosen.jquery.min.js'))

                                ->prependFile('https://maps.googleapis.com/maps/api/js?key=AIzaSyAbgUXX05-ynNUEtjWUvvP4z7SljX7CDKo')
                                ->prependFile($this->basePath('/plugins/bootstrap-select/ajax-bootstrap-select.min.js'));
?>

<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/magnific-popup.css">
<link rel="stylesheet" href="<?php echo $this->basePath()?>/plugins/bootstrap-select/ajax-bootstrap-select.min.css">
<!-- redactor -->
<link rel="stylesheet" href="<?php echo $this->basePath()?>/plugins/redactor/redactor_all_2016.min.css">

<!--Chosen [ OPTIONAL ]-->
<link href="<?php echo $this->basePath()?>/plugins/chosen/chosen.min.css" rel="stylesheet">

<script type="text/javascript">
    
    // *****************************************************
    //URL CLIENTES
    var urlSaveIngClientes          ='<?php echo $this->url("clientes/clientesIngresar"); ?>';
    var urlSaveEdiClientes          ='<?php echo $this->url("clientes/clientesEditar"); ?>';
    var urlEliminarClientes         ='<?php echo $this->url("clientes/clientesEliminar"); ?>';
    var urlGetDataClientes          ='<?php echo $this->url("clientes/clientesGetData"); ?>';
    var urlAutocompleteClientes     ='<?php echo $this->url("clientes/clientesAutorcomplete"); ?>';
    var urlTablaClientes            ='<?php echo $this->url("clientes/clientesTabla"); ?>';
    var global_isLoadTablaClientes  =false;

    var global_noImage='<?php echo $this->basePath()."/img/".$this->NoImage; ?>';

    var global_searchTable='<?php echo addslashes($this->search); ?>';
    var global_startTable='<?php echo $this->startTable; ?>';
    var global_lengthTable='<?php echo $this->lengthTable; ?>';
    var global_orderTable='<?php echo $this->orderTable; ?>';
    var global_orderDirTable='<?php echo ($this->order_dirTable==null)?"desc":$this->order_dirTable; ?>';

    // +++++++++++++++++++++++++++++++++++++++++++++++
    // LIMPIA EL FORMULARIO
    function clearForm()
    {
        document.getElementById("saveClientes").reset();
        $("#clienteHidden").val("0");
        $(".imgCargando").empty();
    }

    function clearClassRow(){
        $("#tablaClientes tr").removeClass("danger");
        $("#tablaClientes tr").removeClass("info");
    }

    // +++++++++++++++++++++++++++++++++++++++++++
    // ENVIA LOS DATOS DE ING-EDIT
    function sendDataAjax(url, formData, cargando, $btn)
    {
        var source   = $("#alert-template").html();
        var template = Handlebars.compile(source);
        var sourceCarg   = $("#imgCargando-template").html();
        var templateCarg = Handlebars.compile(sourceCarg);
        var parent=cargando.parents('.modal');
        $.ajax({
            url: url, 
            dataType: "json",
            type: 'POST',
            data: formData,
            cache: false,
            contentType: false,
            processData: false,
            beforeSend: function(){
                var contextCarg = { };
                cargando.html(templateCarg(contextCarg));
                $btn.button('loading');
            },
            success: function(data){
                $btn.button('reset');

                if(data.status=='ok'){

                    var context = {msj: data.msj, tipo: "alert-success" };
                    cargando.html(template(context));

                    if( parent.attr('id')=='myModalImportarExcel' ){
                        $("#myModalImportarExcel .btn-cerrar-importacion").prop('disabled', false);
                        setTimeout(function(){
                            $("#myModalImportarExcel").modal('hide');
                        },900);
                    }
                    else{
                        setTimeout(function(){
                            $("#myModalClientes").modal('hide');
                        },900);
                    }

                    if(global_isLoadTablaClientes==true){
                        $('#tablaClientes').DataTable().draw(false);
                    }
                }
                else{
                    var context = {msj: data.msj, tipo: "alert-danger" };
                    cargando.html(template(context));

                    //SI RETORNAMOS UN MENSAJE DE ERROR AL MOMENTO DE IMPORTAR
                    if( parent.attr('id')=='myModalImportarExcel' ){
                        $("#myModalImportarExcel .btn-cerrar-importacion").prop('disabled', false);
                    }
                }
            },
            error: function(){
                $btn.button('reset');
                var context = {msj: "Ocurrio un error procesando los datos.", tipo: "alert-danger" };
                cargando.html(template(context));

                //SI OCURRIO UN ERROR AL MOMENTO DE IMPORTAR
                if( parent.attr('id')=='myModalImportarExcel' ){
                    $("#myModalImportarExcel .btn-cerrar-importacion").prop('disabled', false);
                }
            }
            
        });
    }

    function loadDataTablaClientes(){
        
        if( global_isLoadTablaClientes==true ){
            $('#tablaClientes').DataTable().destroy();
        }

        $('#tablaClientes').DataTable({
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": urlTablaClientes,
            "columns": [
                { "data": "nombre" },
                { "data": "fecha" },
                { "data": "version" }
            ],
            "columnDefs": [ { 
                        "targets": 2, 
                        "orderable": false 
            } ],
            "iDisplayStart": parseInt(global_startTable),
            "iDisplayLength": parseInt(global_lengthTable),
            "oSearch": {"sSearch": global_searchTable},
            "order": [ parseInt(global_orderTable), global_orderDirTable ],
            responsive: true,
                "dom": 'T<"clear">lfrtip',
                "tableTools": {
                    "sSwfPath": "<?php echo $this->basePath()?>/js/plugins/dataTables/swf/copy_csv_xls_pdf.swf"
            },
            "oLanguage": {
                "sProcessing":     "Procesando...",
                "sLengthMenu":     "Mostrar _MENU_ registros",
                "sZeroRecords":    "No se encontraron resultados",
                "sEmptyTable":     "Ningún dato disponible en esta tabla",
                "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix":    "",
                "sSearch":         "Buscar:",
                "sUrl":            "",
                "sInfoThousands":  ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst":    "Primero",
                    "sLast":     "Último",
                    "sNext":     "Siguiente",
                    "sPrevious": "Anterior",
                },
                "fnInfoCallback": null,
            },
            "fnDrawCallback": function( oSettings ) {
                // -------------------------------------------------
                // TOOLTIP DE LOS BOTONES
                $('[data-toggle="tooltip"]').tooltip({ html:true });

                $("img.lazy").lazyload({
                    effect: "fadeIn"
                });
            }
        });
        
    }


    function changeNameSlug(){
        var value = $.trim($(this).val());
        value = value.replace(/ /g, "-");
        // $("input[name='client_slug']").val(value.toLowerCase());
    }

    $(document).ready(function(){


        var source   = $("#alert-template").html();
        var template = Handlebars.compile(source);
        var sourceCarg   = $("#imgCargando-template").html();
        var templateCarg = Handlebars.compile(sourceCarg);



        $('.alertaMSJ').delay(2500).slideToggle(2500);

        
        //=========================================================
        loadDataTablaClientes();
        global_isLoadTablaClientes=true;

        // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        // NUEVA
        $(document).on( "click", "#nuevoRegistro", function() {
            $("#saveClientes").attr('action', urlSaveIngClientes);
            $('#myModalClientes').modal({
                backdrop: 'static'
            });
            clearForm();
            $("#myModalClientes .modal-title").text("Nuevo Cliente");
        });

        $('#myModalClientes').on('hide.bs.modal', function () {
            clearClassRow();
            clearForm();

            //habilitamos el campo slug y le agregamos el evento change (se lo quitamos al abrir modal en modo edicion)
            // $("input[name='client_name']").on('change',changeNameSlug);
            // $("input[name='client_slug']").prop('disabled', false);


            //DEJAMOS LA IMAGEN POR DEFECTO
            $('#myModalClientes .img-preview').attr('src',global_noImage)
                .fadeIn();
        });

        //=========================================================
        // FORMATEA EL NOMBRE Y LOS PONE EN EL INPUT SLUG
        // UTILIZA LA FUNCION "CHANGENAMESLUG" PARA REALIZAR ESTO
        // $("input[name='client_name']").on('change',changeNameSlug);
        //===============================================
        // $("input[name='client_slug']").change(function () {
        
        //     var value = $.trim($(this).val());
        //     value = value.replace(/ /g, "-");
        //     $("input[name='client_slug']").val(value.toLowerCase());
        // });
        // -- FIN FORMATEA titulo

        // ++++++++++++++++++++++++++++++++++++++++++++++
        // INGRESA 
        var optionRules={
        };
        var messagesRules={
            client_name: {
                required: "Este campo es requerido.",
                maxlength:"Debe ingresar menos de {0} caracteres."
            },
            // client_slug: {
            //     required: "Este campo es requerido.",
            //     maxlength:"Debe ingresar menos de {0} caracteres."
            // },
        };
        $("#saveClientes").validate({
            option:optionRules,
            messages:messagesRules,
            highlight: function(element, errorClass){ 
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function(element, errorClass){ 
                $(element).closest('.form-group').removeClass('has-error');
            },
            submitHandler: function(form){

                var formData = new FormData( $("#saveClientes")[0] );
                sendDataAjax( $("#saveClientes").attr("action") , formData, $("#myModalClientes .imgCargando"), $("#myModalClientes .btnSave"));
            }
        });

        // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        // LOAD DATOS PARA EDITAR REGION
        $( "#tablaClientes" ).on( "click", ".linkEditar", function() {
            
            // var source   = $("#icon-selected-template").html();
            // var template = Handlebars.compile(source);

            clearForm();
            var data=$(this).attr('data');
            $("#tablaClientes #row_"+data).addClass("info");

            $("#saveClientes").attr('action', urlSaveEdiClientes);
            $('#myModalClientes').modal({
                backdrop: 'static'
            });
            // +++++++++++++++++++++++++++++++++++++
            $("#myModalClientes .modal-title").text("Editar Cliente");

            // ++++++++++++++++++++++++++++++++++++++
            // MENSAJE CARGANDO
            $("#myModalClientes .imgCargando").html(templateCarg( {} ));

            //deshabilitamos el campo slug y le quitamos el evento change (se lo volvemos a agregar al cerrar modal)
            // $("input[name='client_slug']").prop('disabled', true);
            // $("input[name='client_name']").off('change',changeNameSlug);


            // ----------------------------------------------
            // ENVIA PETICION
            $.post( urlGetDataClientes, { cliente: data }, function( data ) {

                $("#myModalClientes .imgCargando").empty();
                if (data.status=="ok") {
                    
                    $("#client_name").val( data.client_name );
                    // $("#client_slug").val( data.client_slug );

                    $("#clienteHidden").val( data.id );


                }else{
                    var context = {msj: data.msj, tipo: "alert-danger" };
                    $("#myModalClientes .imgCargando").html(template(context));
                }

            }, "json").fail(function(){
                console.log('Error en el servidor');
                $("#myModalClientes .imgCargando").empty();
            });
        });

        
        //========================================================================
        //ELIMINA
        $('#tablaClientes').on('click', '.linkEliminar',function () {
            var id=$(this).attr('data');
            $("#tablaClientes #row_"+id).addClass("danger");
            swal({
                title: "¿Eliminar?",
                text: "Estas seguro de eliminar este cliente?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Si, Eliminar",
                cancelButtonText: "Cancelar",
                closeOnConfirm: false,
                showLoaderOnConfirm: true,
            }, function (isConfirm) {
                if (isConfirm) {
                    $.post( urlEliminarClientes, { cliente: id }, function( data ) {
                        if (data.status=="ok") {

                            swal("Eliminado!", data.msj, "success");
                            setTimeout(function(){
                                $('#tablaClientes').DataTable().draw(false);
                            }, 700);
                            clearClassRow();
                        }
                        else{
                            swal("Error", data.msj, "error");
                            clearClassRow();
                        }
                        
                    }, "json").fail(function(){
                        clearClassRow();
                        console.log('Error en el server');
                        swal("Error", 'Error en el servidor (contacte a su administrador).', "error");
                    });
                }
                else{
                    clearClassRow();
                }
                
            });
        });
        

    });

</script>

<!-- MODAL CLIENTES -->
<div id="myModalClientes" class="modal inmodal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog ">
        <div class="modal-content" >
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title"></h4>
            </div>

            <!-- ICON CARGANDO -->
            <div class="panel-alert">
                <div class="imgCargando" class="alert-wrap in"></div>
            </div>
            <!-- /.FIN ICON CARGANDO -->
            
            <form id="saveClientes" action="" method="POST" enctype="multipart/form-data">

                <div class="modal-body" >
                    
                    <div class="row">
                        <div class="col-md-12">
                            <br />
                            <div class="form-group">
                                <label for="client_name" class="text-semibold">Nombre *</label>
                                <input type="text" class="form-control" name="client_name" id="client_name" maxlength="200" required />
                            </div>
                            
                            <!-- <div class="form-group">
                                <label for="client_slug" class="text-semibold">Slug *</label>
                                <input type="text" class="form-control" name="client_slug" id="client_slug" maxlength="200" required />
                            </div> -->
                                    
                            <input type="hidden" value="0" id="clienteHidden" name="clienteHidden" />
                            <br />
                        </div>
                        
                    </div>
                </div>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal" >Cerrar</button>
                    <button 
                        class="btn btn-primary btn-sm btnSave" 
                        data-loading-text="<i class='fa fa-spinner fa-pulse fa-fw'></i> Guardando">
                        <i class="fa fa-floppy-o"></i> Guardar
                    </button>
                </div>
            </form>

        </div>
    </div>
</div>


