<?php 
    if (defined('RUNNING_FROM_ROOT')) {
        $this->plugin('basePath')->setBasePath($this->basePath().'/public');
    }       
?>


<script type="text/javascript" charset="utf-8">
    $(document).ready(function() {
        $('.alertaMSJ').delay(2000).slideToggle(2500);

    });
</script>

<?php

$flash=$this->flashMessenger()
            ->setMessageOpenFormat('<div%s id="alertaMSJ"><strong>')
            ->setMessageSeparatorString('')
            ->setMessageCloseString('</strong></div>');
?>


<!-- PASSWORD RESETTING FORM -->
<!--===================================================-->
<div class="cls-content">
    <div class="cls-content-sm panel">
        <div class="panel-body">
            <p class="pad-btm">Ingresa tu Correo para recuperar tu contraseña.</p>
            <?php echo $flash->render('msjExito',array('alert', 'alert-success', 'alertaMSJ'));?> 
            <?php echo $flash->render('msjError',array('alert', 'alert-danger', 'alertaMSJ'));?> 
            <form method="POST" action="<?=$this->url("recuperar")?>">
                <div class="form-group">
                    <div class="input-group">
                        <div class="input-group-addon"><i class="fa fa-envelope"></i></div>
                        <input type="email" class="form-control" maxlength="200" name="correoUser" id="correoUser" placeholder="Correo" required="">
                    </div>
                </div>
                <div class="form-group text-right">
                    <button class="btn btn-success text-uppercase" type="submit">Enviar</button>
                </div>
            </form>
        </div>
    </div>
    <div class="pad-ver">
        <a href="<?=$this->url("login")?>" class="btn-link mar-rgt">Volver al login</a>
    </div>
</div>
<!--===================================================-->
        
