<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Menciones\Module'                        	=> __DIR__ . '/Module.php',
    'Menciones\Controller\MencionesController' 	=> __DIR__ . '/src/Menciones/Controller/MencionesController.php'
);