<?php 
	if (defined('RUNNING_FROM_ROOT')) {
        $this->plugin('basePath')->setBasePath($this->basePath().'/public');
    }    

?>

<script>
    
    function selectInCombo(combo,val)
    {
        for(var indice=0 ;indice<document.getElementById(combo).length;indice++)
        {
            if (document.getElementById(combo).options[indice].value==val ){
                document.getElementById(combo).selectedIndex =indice;
            }
        }
    }

</script>

<?php
    $flash=$this->flashMessenger()
            ->setMessageOpenFormat('<div%s id="alertaMSJ"><strong>')
            ->setMessageSeparatorString('')
            ->setMessageCloseString('</strong></div>');
?>


<?php echo $flash->render('msjError',array('alert', 'alert-danger', 'alertaMSJ'));?>
<?php echo $flash->render('msjExito',array('alert', 'alert-success', 'alertaMSJ'));?>


<!--Page Title-->
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<div id="page-title">
    <h1 class="page-header text-overflow">CAMPAÑAS</h1>
</div>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<!--End page title-->

<!--Breadcrumb-->
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<ol class="breadcrumb">
    <li><a href="<?php echo $this->url('campanas').$this->queryGET ?>">Campañas</a></li>
    <li>Detalle - <?php echo stripslashes($campana["campaign_title"]) ?></li>
</ol>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<!--End breadcrumb-->

<!--Page content-->
<!--===================================================-->
<div id="page-content">
    <div class="row">
        <div class="col-lg-3 col-md-4">
            <div class="panel widget">
                <div class="widget-header bg-gray">
                    
                </div>
                <div class="widget-body text-center">
                    

                    <h4 class="mar-no text-overflow" title="<?php echo $this->escapeHtmlAttr(stripslashes($campana["campaign_title"])) ?>">
                        <?php echo stripslashes($campana["campaign_title"]) ?>
                    </h4>
                    <p class="text-muted mar-btm">
                        <i class='fa fa-user'></i> 
                        <?php echo stripslashes($campana["client_name"]) ?>
                        <br />
                        <?php 
                            if( !empty($campana['radio_name']) )
                                echo '<em>'.stripslashes($campana["radio_name"]).'</em>';
                        ?>
                    </p>

                    <p>
                        <label class="label" style='background: <?php echo stripslashes($campana['campaign_color']); ?> !important' >Color distintivo</label>
                    </p>

                    <div class="pad-ver">
                        <?php if( (int)$campana["campaign_status"]==1): ?>
                            <label class="label label-table label-success"><em class="text-white">HABILITADO</em></label>
                        <?php else: ?>
                            <label class="label label-table label-danger"><em class="text-white">DESHABILITADO</em></label>
                        <?php endif; ?>
                    </div>

                    <ul class="list-group bg-trans">
                        <li class="list-group-item list-item-sm">
                            <i class="fa fa-calendar-o fa-fw"></i> <?php echo $campana["campaign_date_create_fecha"].' - '.$campana["campaign_date_create_hora"] ?>
                        </li>
                    </ul>
                    

                </div>
            </div>

        </div>


        <div class="col-lg-9 col-md-8">

            <div class="well well-sm">
                <a 
                    href="<?php echo $this->url('campanas').$this->queryGET ?>" 
                    data-toggle="tooltip" 
                    data-placement="top" 
                    title="Regresar al listado" 
                    class="btn btn-default btn-icon fa fa-arrow-left">
                    Volver
                </a>
            </div>
            
            <div class="tab-base">
                    
                <!--Nav tabs-->
                <ul class="nav nav-tabs tabs-right">

                    <li class="active">
                        <a data-toggle="tab" href="#tab-menciones">
                            <i class="fa fa-commenting-o"></i> MENCIONES <span class="badge badge-primary js_t_menciones"><?php echo (int)$campana['t_menciones'] ?></span>
                        </a>
                    </li>

                    <li class="">
                        <a data-toggle="tab" href="#tab-agenda">
                            <i class="fa fa-calendar"></i> AGENDA
                        </a>
                    </li>
                    
                </ul>

                <!--Tabs Content-->
                <div class="tab-content">
                    
                    <div id="tab-menciones" class="tab-pane fade active in">

                        <div class="well well-sm">
                            <button class="btn btn-primary btn-sm pull-right" id="nuevoRegistro"><i class="fa fa-plus"></i> Nueva</button>
                            <br />
                            <br />
                        </div>
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered" id="tablaMenciones"  cellspacing="0" width="100%">
                                <thead>
                                    <tr>
                                        <th style="width:400px;">EXTRACTO</th>
                                        <th>ESTADO</th>
                                        <th>FECHA</th>
                                        <th>ACCIÓN</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    
                                </tbody>
                            </table>
                        </div>
                    </div>

                    <div id="tab-agenda" class="tab-pane fade">
                        
                        <div class="mar-btm">
                            <h4 class="text-thin text-bold">Simbologia</h4>
                            <span class="label mar-top mar-btm text-bold" style="background-color:#c3cedb;">Mención Expirada</span>
                        </div>

                        <!-- Calendar placeholder-->
                        <!-- ============================================ -->
                        <div id='calendario-menciones'></div>
                        <!-- ============================================ -->

                    </div>

                </div>

            </div>


        </div>
    </div>
    

</div>
<!--===================================================-->
<!--End page content-->


<style>
    .font-larger{
        font-size: larger;
    }
</style>

<?php 
    echo $this->inlineScript()->prependFile($this->basePath('js/jquery.magnific-popup.min.js'))
                                ->prependFile($this->basePath('plugins/jquery-validation/additional-methods.min.js'))
                                ->prependFile($this->basePath('plugins/jquery-validation/jquery.validate.min.js'))

                                ->prependFile($this->basePath('plugins/dropzone/dropzone.min.js'))
                                ->prependFile($this->basePath('plugins/bootstrap-timepicker/bootstrap-timepicker.min.js'))
                                ->prependFile($this->basePath('plugins/bootstrap-datepicker/bootstrap-datepicker.js'))

                                ->prependFile($this->basePath('plugins/fullcalendar/fullcalendar.min.js'))
                                ->prependFile($this->basePath('plugins/fullcalendar/lib/jquery-ui.custom.min.js'))
                                ->prependFile($this->basePath('plugins/fullcalendar/lib/moment.min.js'))


                                ->prependFile($this->basePath('/plugins/bootstrap-select/ajax-bootstrap-select.min.js'))
                                ->prependFile($this->basePath('/plugins/bootstrap-select/bootstrap-select.min.js'));
?>

<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/magnific-popup.css">

<!-- SELECT BOOTSTRAP -->
<link rel="stylesheet" href="<?php echo $this->basePath()?>/plugins/bootstrap-select/bootstrap-select.min.css">
<link rel="stylesheet" href="<?php echo $this->basePath()?>/plugins/bootstrap-select/ajax-bootstrap-select.min.css">

<!--Dropzone [ OPTIONAL ]-->
<link href="<?php echo $this->basePath(); ?>/plugins/dropzone/dropzone.css" rel="stylesheet">

<!--Bootstrap Timepicker [ OPTIONAL ]-->
<link href="<?php echo $this->basePath(); ?>/plugins/bootstrap-timepicker/bootstrap-timepicker.min.css" rel="stylesheet">

<!--Bootstrap Datepicker [ OPTIONAL ]-->
<link href="<?php echo $this->basePath(); ?>/plugins/bootstrap-datepicker/bootstrap-datepicker.css" rel="stylesheet">

<!--Full Calendar [ OPTIONAL ]-->
<link href="<?php echo $this->basePath(); ?>/plugins/fullcalendar/fullcalendar.css" rel="stylesheet">

<script type="text/javascript">
    
    // *****************************************************
    //URL MENCIONES
    var urlSaveIngMencion               = '<?php echo $this->url("menciones/mencionesIngresar"); ?>';
    var urlSaveEdiMencion               = '<?php echo $this->url("menciones/mencionesEditar"); ?>';
    var urlEliminarMencion              = '<?php echo $this->url("menciones/mencionesEliminar"); ?>';
    var urlGetDataMencion               = '<?php echo $this->url("menciones/mencionesGetData"); ?>';
    var urlStatusMencion                = '<?php echo $this->url("menciones/mencionesStatus"); ?>';
    var urlTablaMencion                 = '<?php echo $this->url("menciones/mencionesTabla"); ?>';
    var urlCalendarioMencion            ='<?php echo $this->url("menciones/mencionesCalendario"); ?>';
    var global_isLoadTablaMenciones     = false;
    var global_isLoadCalendarioMencion  = false;

    // *****************************************************
    //URL HORARIOS
    var urlEliminarHorario              = '<?php echo $this->url("horarios/horariosEliminar"); ?>';

    var global_noImage='<?php echo $this->basePath()."/img/".$this->NoImage; ?>';
    var global_campana='<?php echo $campana["idcamp"] ?>';

    function clearClassRow(tabla_name){
        if(!tabla_name){
            return false;
        }
        $("#"+tabla_name+" tr").removeClass("danger");
        $("#"+tabla_name+" tr").removeClass("info");
    }

    // +++++++++++++++++++++++++++++++++++++++++++++++
    // LIMPIA EL FORMULARIO
    function clearForm()
    {
        document.getElementById("saveMencion").reset();
        $("#mencionHidden").val("0");
        $(".imgCargando").empty();
    }

    // +++++++++++++++++++++++++++++++++++++++++++
    // ENVIA LOS DATOS DE ING-EDIT
    function sendDataAjax(url, formData, cargando, $btn)
    {
        var source          = $("#alert-template").html();
        var template        = Handlebars.compile(source);
        var sourceCarg      = $("#imgCargando-template").html();
        var templateCarg    = Handlebars.compile(sourceCarg);
        var parent          = cargando.parents('.modal');

        $.ajax({
            url: url, 
            dataType: "json",
            type: 'POST',
            data: formData,
            cache: false,
            contentType: false,
            processData: false,
            beforeSend: function(){
                var contextCarg = { };
                cargando.html(templateCarg(contextCarg));
                $btn.button('loading');
            },
            success: function(data){
                $btn.button('reset');

                if(data.status=='ok'){

                    var context = {msj: data.msj, tipo: "alert-success" };
                    cargando.html(template(context));

                    if(typeof data.t_menciones!='undefined' ){
                        $(".js_t_menciones").text(data.t_menciones);
                    }

                    //REFRESCAMOS EL CALENDARIO SOLO SI FUE DIBUJADO EN EL TAB Y NOS ENCONTRAMOS DENTRO DE ESTE
                    if(global_isLoadCalendarioMencion==true && $(".nav-tabs li a[href='#tab-agenda']").parent().hasClass('active') ){
                        $("#calendario-menciones").fullCalendar( 'refetchEvents' );
                    }
                    //REFRESCAMOS LA TABLA SOLO SI ESTAMOS DENTRO DEL LISTADO
                    if(global_isLoadTablaMenciones==true && $(".nav-tabs li a[href='#tab-menciones']").parent().hasClass('active') ){
                        $('#tablaMenciones').DataTable().draw(false);
                    }

                    setTimeout(function(){
                        $("#myModalMenciones").modal('hide');
                    },500);
                }
                else{
                    var context = {msj: data.msj, tipo: "alert-danger" };
                    cargando.html(template(context));
                }
            },
            error: function(){
                $btn.button('reset');
                var context = {msj: "Ocurrio un error procesando los datos.", tipo: "alert-danger" };
                cargando.html(template(context));
            }
            
        });
    }

    function loadDataTablaMenciones(){
        
        if( global_isLoadTablaMenciones==true ){
            $('#tablaMenciones').DataTable().destroy();
        }

        $('#tablaMenciones').DataTable({
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": urlTablaMencion,
            "columns": [
                { "data": "extracto" },
                { "data": "estado" },
                { "data": "fecha" },
                { "data": "version" }
            ],
            "columnDefs": [ { 
                        "targets": 3, 
                        "orderable": false 
            } ],
            "order": [ 2, "desc" ],
            responsive: true,
            "dom": 'T<"clear">lfrtip',
            "tableTools": {
                "sSwfPath": "<?php echo $this->basePath()?>/js/plugins/dataTables/swf/copy_csv_xls_pdf.swf"
            },
            "fnServerParams": function (aoData) { 
                aoData.push({ "name": 'campana', "value": global_campana });
            },
            "oLanguage": {
                "sProcessing":     "Procesando...",
                "sLengthMenu":     "Mostrar _MENU_ registros",
                "sZeroRecords":    "No se encontraron resultados",
                "sEmptyTable":     "Ningún dato disponible en esta tabla",
                "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix":    "",
                "sSearch":         "Buscar:",
                "sUrl":            "",
                "sInfoThousands":  ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst":    "Primero",
                    "sLast":     "Último",
                    "sNext":     "Siguiente",
                    "sPrevious": "Anterior",
                },
                "fnInfoCallback": null,
            },
            "fnDrawCallback": function( oSettings ) {
                // -------------------------------------------------
                // TOOLTIP DE LOS BOTONES
                $('#tablaMenciones [data-toggle="tooltip"]').tooltip({ html:true });

                $("#tablaMenciones img.lazy").lazyload({
                    effect: "fadeIn"
                });
            }
        });
        
    }


    function deleteData(url, datos, tabla_name, textos_swal, $element_remove){

        swal({
            title: "¿Eliminar?",
            text: textos_swal.text,
            type: "warning",
            showCancelButton: true,
            confirmButtonColor: "#DD6B55",
            confirmButtonText: "Si, Eliminar",
            cancelButtonText: "Cancelar",
            closeOnConfirm: false,
            showLoaderOnConfirm: true,
        }, function (isConfirm) {
            if (isConfirm) {
                $.post( url, datos, function( data ) {
                    if (data.status=="ok") {

                        swal("Eliminado!", data.msj, "success");
                        
                        if(typeof data.t_menciones!='undefined' ){
                            $(".js_t_menciones").text(data.t_menciones);
                        }

                        //******************************************************
                        //SI EXISTE UN NOMBRE DE TABLA ENTRA
                        if(tabla_name){
                            setTimeout(function(){
                                $('#'+tabla_name).DataTable().draw(false);
                            }, 700);
                        }
                        //******************************************************

                        //******************************************************
                        //SI HAY UN ELEMENTO PARA ELIMINAR DEL HTML
                        if($element_remove){
                            $element_remove.remove();
                        }
                        //******************************************************

                    }
                    else{
                        swal("Error", data.msj, "error");
                    }
                    clearClassRow(tabla_name);
                    
                }, "json").fail(function(){
                    clearClassRow(tabla_name);
                    console.log('Error en el server');
                    swal("Error", 'Error en el servidor (contacte a su administrador).', "error");
                });
            }
            else{
                clearClassRow(tabla_name);
            }
            
        });
    }

    function loadtimePicker(){
        // BOOTSTRAP TIMEPICKER - COMPONENT
        // =================================================================
        // Require Bootstrap Timepicker
        // http://jdewit.github.io/bootstrap-timepicker/
        // =================================================================
        $('.js-mention_schedule').timepicker({
            minuteStep      : 1,
            showInputs      : false,
            disableFocus    : true,
            maxHours        : 24,
            defaultTime     : 'current',
            showMeridian    : false,
            appendWidgetTo  : $("#myModalMenciones"),
        });
    }


    $(document).ready(function(){

        var source   = $("#alert-template").html();
        var template = Handlebars.compile(source);
        var sourceCarg   = $("#imgCargando-template").html();
        var templateCarg = Handlebars.compile(sourceCarg);

        //INICIALIZAMOS TOOLTIP
        $('[data-toggle="tooltip"]').tooltip({ html:true });


        $('.alertaMSJ').delay(2500).slideToggle(2500);

        // BOOTSTRAP DATEPICKER WITH AUTO CLOSE
        // =================================================================
        // Require Bootstrap Datepicker
        // http://eternicode.github.io/bootstrap-datepicker/
        // =================================================================
        $('#mention-range .input-daterange').datepicker({
            format          : "yyyy-mm-dd",
            todayBtn        : "linked",
            autoclose       : true,
            todayHighlight  : true,
            language        : 'es',
            container       : $("#myModalMenciones")
        }).on('hide.bs.modal', function(event){
            //AL CERRARSE EL MODAL DE LAS FECHAS, EJECUTABA FUNCIONES QUE SE EJECUTAN AL CERRAR EL MODAL DE RESERVA
            //POR ESTO SE DETIENE LA PROPAGACION DEL EVENTO HIDE
            event.stopPropagation();
        });

        

        //=========================================================
        loadDataTablaMenciones();
        global_isLoadTablaMenciones=true;
        //=========================================================

        //========================================================================
        //ELIMINA
        $('#tablaMenciones').on('click', '.linkEliminar',function () {
            var datos={};
            var textos_swal={
                text : ''
            }
            if( $(this).parents('table').attr('id')=='tablaMenciones' ){

                var mencion      = $(this).attr('data');
                datos.mencion    = mencion;

                $("#tablaMenciones #row_"+mencion ).addClass("danger");
                textos_swal.text='Estas seguro de eliminar esta mención?';

                deleteData(urlEliminarMencion, datos, 'tablaMenciones', textos_swal, false);
            }
        });

        // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        // NUEVA
        $(document).on( "click", "#nuevoRegistro", function() {
            $("#saveMencion").attr('action', urlSaveIngMencion);
            $('#myModalMenciones').modal({
                backdrop: 'static'
            });
            $("#myModalMenciones .modal-title").text("Nueva Mención");
        });

        $('#myModalMenciones').on('hide.bs.modal', function () {
            clearClassRow('tablaMenciones');
            clearForm();

            //LIMPIAMOS LOS CHECKBOX
            $(".js-mention_days").prop('checked', false);
            $(".js-mention_days").parent().removeClass('active');

            //QUITAMOS LOS ERRORES DEL FORMULARIO
            $("#myModalMenciones .form-group").removeClass('has-error');
            $("#myModalMenciones .form-group .error").remove();

            $("#myModalMenciones .div-content-extra-data").empty();

            $("input[name='mention_date_start']").datepicker('setDate', '');
            $("input[name='mention_date_end']").datepicker('setDate', '');
        });


        // ++++++++++++++++++++++++++++++++++++++++++++++
        // INGRESA 
        var optionRules={
        };
        var messagesRules={
            mention_description: {
                required: "Este campo es requerido.",
                maxlength:"Debe ingresar menos de {0} caracteres."
            },
        };
        $("#saveMencion").validate({
            option:optionRules,
            messages:messagesRules,
            highlight: function(element, errorClass){ 
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function(element, errorClass){ 
                $(element).closest('.form-group').removeClass('has-error');
            },
            submitHandler: function(form){

                var formData = new FormData( $("#saveMencion")[0] );
                sendDataAjax( $("#saveMencion").attr("action") , formData, $("#myModalMenciones .imgCargando"), $("#myModalMenciones .btnSave"));
            }
        });

        // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        // LOAD DATOS PARA EDITAR
        $( "#tablaMenciones" ).on( "click", ".linkEditar", function() {
            

            var data=$(this).attr('data');
            $("#tablaMenciones #row_"+data).addClass("info");

            $("#saveMencion").attr('action', urlSaveEdiMencion);
            $('#myModalMenciones').modal({
                backdrop: 'static'
            });
            // +++++++++++++++++++++++++++++++++++++
            $("#myModalMenciones .modal-title").text("Editar Mención");

            // ++++++++++++++++++++++++++++++++++++++
            // MENSAJE CARGANDO
            $("#myModalMenciones .imgCargando").html(templateCarg( {} ));
            

            // ----------------------------------------------
            // ENVIA PETICION
            $.post( urlGetDataMencion, { mencion: data }, function( data ) {

                $("#myModalMenciones .imgCargando").empty();
                if (data.status=="ok") {
                    
                    $("#mention_description").val( data.mention_description );
                    $("#mencionHidden").val( data.id );

                    $("input[name='mention_date_start']").val( data.mention_date_start );
                    $("input[name='mention_date_start']").datepicker('setDate', data.mention_date_start);

                    $("input[name='mention_date_end']").val( data.mention_date_end );
                    $("input[name='mention_date_end']").datepicker('setDate', data.mention_date_end);

                    //SELECCIONAMOS LOS DIAS
                    for (var i = 0; i < data.mention_days.length; i++) {
                        var dia = data.mention_days[i]
                        $.each( $('.js-mention_days'), function(){
                            if( $(this).val()==dia ){
                                //LIMPIAMOS LOS CHECKBOX
                                $(this).prop('checked', true);
                                $(this).parent().addClass('active');
                            }
                        });
                    };

                    if(data.t_mention_schedule>0){

                        var source_mencion   = $("#mencion-extra-data-template").html();
                        var template_mencion = Handlebars.compile(source_mencion);

                        for (var i = 0; i < data.mention_schedule.length; i++) {
                            var schedule = data.mention_schedule[i]
                            //*************************************
                            //AGREGAMOS LA INFORMACION ADICIONAL
                            var contenido={
                                mention_schedule    : schedule.hora,
                                mention_schedule_id : schedule.id,
                                disabled            : 'disabled',
                            };
                            $("#myModalMenciones .div-content-extra-data").append( template_mencion(contenido) );
                            //*************************************
                        };
                        //***********************************************
                        //DESTRUYE NANO SCROLL
                        $(".nano").nanoScroller({ destroy: true });
                        //INICIALIZA NANO SCROLL
                        $(".nano").nanoScroller({alwaysVisible: true});
                        //***********************************************
                        loadtimePicker();
                    }

                }else{
                    var context = {msj: data.msj, tipo: "alert-danger" };
                    $("#myModalMenciones .imgCargando").html(template(context));
                }

            }, "json").fail(function(){
                console.log('Error en el servidor');
                $("#myModalMenciones .imgCargando").empty();
            });
        });
    
        //========================================================================
        //deshabilita - habilita
        $('#tablaMenciones').on('click', '.linkStatus',function () {
            var id=$(this).attr('data');
            $("#tablaMenciones #row_"+id).addClass("danger");

            var text="Estas seguro de deshabilitar esta mención?";
            var confirmButtonText="Si, Deshabilitar";
            var confirmButtonColor="#DD6B55";
            var title='¿Deshabilitar?';
            var titleExito="Deshabilitada!";
            if($(this).attr('data-status')=='deshabilitado'){
                text="Estas seguro de habilitar esta mención?";
                confirmButtonText="Si, Habilitar";
                confirmButtonColor="#1ab394";
                title='¿Habilitar?';
                titleExito="Habilitada!";
            }
            swal({
                title: title,
                text: text,
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: confirmButtonColor,
                confirmButtonText: confirmButtonText,
                cancelButtonText: "Cancelar",
                closeOnConfirm: false,
                showLoaderOnConfirm: true,
            }, function (isConfirm) {
                if (isConfirm) {
                    $.post( urlStatusMencion, { mencion: id }, function( data ) {
                        if (data.status=="ok") {

                            swal(titleExito, data.msj, "success");
                            setTimeout(function(){
                                $('#tablaMenciones').DataTable().draw(false);
                            }, 700);
                            clearClassRow('tablaMenciones');
                        }
                        else{
                            swal("Error", data.msj, "error");
                        }
                        

                    }, "json").fail(function(){
                        console.log('Error en el server');
                        swal("Error", 'Error en el servidor (contacte a su administrador).', "error");
                    });
                }else{
                    clearClassRow('tablaMenciones');
                }
                
            });
        });

        //************************************************************
        //ZONA ADD CAMPOS DINAMICOS
        //AGREGA Y ELIMINA LA TABLA DE NUEVOS DATOS
        $("#myModalMenciones").on('click', '.btnAddCampos', function(){

            var source   = $("#mencion-extra-data-template").html();
            var template = Handlebars.compile(source);

            //*************************************
            //AGREGAMOS LA INFORMACION ADICIONAL
            var contenido={
                mention_schedule    : '',
                mention_schedule_id : '',
                disabled            : '',
            };
            $("#myModalMenciones .div-content-extra-data").append( template(contenido) );
            //*************************************

            //***********************************************
            //DESTRUYE NANO SCROLL
            $(".nano").nanoScroller({ destroy: true });
            //INICIALIZA NANO SCROLL
            $(".nano").nanoScroller({alwaysVisible: true});
            //***********************************************
            
            loadtimePicker();
        });
        $("#myModalMenciones").on('click', '.btnRemoveExtraData', function(){
            var $div_element = $(this).parent();
            if( $(this).data('hora')=='' ){
                $div_element.remove();
            }
            else{
                var datos={};
                var textos_swal={
                    text : ''
                }

                var horario      = $(this).data('hora');
                datos.horario    = horario;

                textos_swal.text='Estas seguro de eliminar este horario?';
                deleteData(urlEliminarHorario, datos, false, textos_swal, $div_element);
                
            }
        });
        // .- FIN AGREGA Y ELIMINA LA TABLA DE NUEVOS DATOS


        //*****************************************************************
        //ZONA CALENDARIO
        //*****************************************************************

        /* initialize the calendar
        -----------------------------------------------------------------*/
        var date = new Date();
        var d = date.getDate();
        var m = date.getMonth();
        var y = date.getFullYear();

        $('#calendario-menciones').fullCalendar({
            header: {
                left: 'prev,next today',
                center: 'title',
                right: 'month,agendaWeek,agendaDay'
            },
            lang: 'es',
            editable: false,
            droppable: true, // this allows things to be dropped onto the calendar
            timeFormat: 'H:mm',
            setHours: 1,
            eventLimit: 7,
            eventSources: [
                {
                    url: urlCalendarioMencion,
                    type: 'GET',
                    data: function() { // a function that returns an object
                        //PARA ENVIAR VALORES DINAMICOS
                        return {
                            // campus:1,
                            // usuario: $("#user_calendar").val(),
                        };
                    },
                    beforeSend: function(){
                        // $global_btnFilter=$(".btnFilterCalendar").button('loading');
                    },
                    success: function(){
                        // console.log('calendario refrescado');
                        // $global_btnFilter.button('reset');
                    },
                    error: function() {
                        // alert('there was an error while fetching events!');
                        console.log('Error al cargar');
                    },
                }
            ] ,
            eventConstraint: {
                start: date,
                end: '3000-01-01' // hard coded goodness unfortunately
            },
            eventClick: function(event, element) {
                if(event.old=='false'){
                    if( $("#checkRemove").is(":checked") ){
                        // deleteReserva(event);
                    }
                    else{
                        var datos={
                            mencion : event.id
                        };
                        getDataView(datos);
                    }
                }
            },
            eventMouseover : function(data, event, view) {
                // var hourStart=moment(data.start._i).format('HH:mm');
                var hourStart ='';
                var start_f   = moment(data.start._i).format('DD-MM-YYYY');
                var end_f     = moment(data.end._i).format('DD-MM-YYYY');

                var content = 
                    '<h4>'+hourStart+data.title+'</h4>'+
                    '<p>['+ start_f +' - '+ end_f +']</p>'+
                    '<p>'+data.description +'<p>';

                $(this).attr('data-toggle', 'tooltip');
                $(this).attr('data-placement', 'top');
                $(this).tooltip({ 
                    html:true,
                    title:content 
                });
                $(this).tooltip('show');
            },
            eventMouseout: function( event, jsEvent, view){
                // console.log($(this) );
            },
        });
        
        //*********************************************************************
        //REDIBUJAMOS EL CALENDARIO O LA TABLA (SEGUN EL TAB SELECCIONADO)
        $(".nav-tabs li a").click(function(){
            if( $(this).attr('href')=='#tab-agenda' ){
                setTimeout(function(){
                    if( global_isLoadCalendarioMencion==false ){
                        $('#calendario-menciones').fullCalendar('render');
                        global_isLoadCalendarioMencion=true;
                    }
                    else{
                        $("#calendario-menciones").fullCalendar( 'refetchEvents' );
                    }
                },200);
            }
            else if( global_isLoadTablaMenciones==true ){
                $('#tablaMenciones').DataTable().draw(false);
            }
        });
        //*********************************************************************

        $('#tablaMenciones').on('click', '.linkView', function(e){
            e.preventDefault();
            if( $(this).attr('data')!='' ){
                var datos={
                    mencion : $(this).attr('data')
                };
                getDataView(datos);
            }
        });
    });

</script>

<!-- MODAL MENCIONES -->
<div id="myModalMenciones" class="modal inmodal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content" >
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title"></h4>
            </div>

            <!-- ICON CARGANDO -->
            <div class="panel-alert">
                <div class="imgCargando" class="alert-wrap in"></div>
            </div>
            <!-- /.FIN ICON CARGANDO -->
            
            <form id="saveMencion" action="" method="POST" enctype="multipart/form-data">

                <div class="modal-body" >
                    
                    <div class="row">

                        <div class="col-lg-7 bord-rgt">

                            <div class="row">
                                <div class="col-lg-12" >
                                    <label class="text-bold">Ingrese el periodo</label>
                                    <div id="mention-range">
                                        <div class="input-daterange input-group" id="datepicker">
                                            <input type="text" class="form-control" name="mention_date_start" />
                                            <span class="input-group-addon">Entre</span>
                                            <input type="text" class="form-control" name="mention_date_end" />
                                        </div>
                                    </div>
                                </div>

                                <div class="col-lg-12 pad-top">
                                    <h5>Seleccione los días en los que se repitirá</h5>
                                    
                                    <?php for($i=1; $i<=7; $i++): ?>
                                        <?php $arr_dias=array('Lunes', 'Martes', 'Miercoles', 'Jueves', 'Viernes', 'Sabado', 'Domingo') ?>
                                        
                                        <div class="checkbox">
                                            <label class="form-checkbox form-normal form-primary form-text mar-rgt text-semibold">
                                                <input type="checkbox" class="js-mention_days" name="mention_days[]" value="<?php echo (int)$i ?>"> <?php echo $arr_dias[$i-1]; ?>
                                            </label>
                                        </div>
                                        
                                    <?php endfor; ?>
                                </div>
                            </div>

                            <div class="form-group mar-top">
                                <label for="mention_description" class="text-bold">Mención *</label>
                                <textarea class="form-control" name="mention_description" id="mention_description" maxlength="60000" cols="30" rows="10" required></textarea>
                            </div>


                            <input type="hidden" value="0" id="mencionHidden" name="mencionHidden" />
                            <input type="hidden" value="<?php echo $campana['idcamp']; ?>" id="campanaHidden" name="campanaHidden" />
                            
                        </div>

                        <div class="col-lg-5">
                            <h4>Horarios</h4>
                            <button type="button" class="btn btn-sm btn-block btn-success btnAddCampos"><i class="fa fa-plus"></i> Agregar Hora</button>
                            <div class="mar-top nano" style="height:500px;">
                                <div class="nano-content div-content-extra-data">
                                    
                                </div>
                            </div>
                        </div>
                    
                    </div>

                </div>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal" >Cerrar</button>
                    <button 
                        class="btn btn-primary btn-sm btnSave" 
                        data-loading-text="<i class='fa fa-spinner fa-pulse fa-fw'></i> Guardando">
                        <i class="fa fa-floppy-o"></i> Guardar
                    </button>
                </div>
            </form>

        </div>
    </div>
</div>
