<?php 
	if (defined('RUNNING_FROM_ROOT')) {
        $this->plugin('basePath')->setBasePath($this->basePath().'/public');
    }    

?>

<script>
    
    function selectInCombo(combo,val)
    {
        for(var indice=0 ;indice<document.getElementById(combo).length;indice++)
        {
            if (document.getElementById(combo).options[indice].value==val ){
                document.getElementById(combo).selectedIndex =indice;
            }
        }
    }

</script>

<?php
    $flash=$this->flashMessenger()
            ->setMessageOpenFormat('<div%s id="alertaMSJ"><strong>')
            ->setMessageSeparatorString('')
            ->setMessageCloseString('</strong></div>');
?>


<?php echo $flash->render('msjError',array('alert', 'alert-danger', 'alertaMSJ'));?>
<?php echo $flash->render('msjExito',array('alert', 'alert-success', 'alertaMSJ'));?>


<!--Page Title-->
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<div id="page-title">
    <h1 class="page-header text-overflow">CAMPAÑAS</h1>
</div>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<!--End page title-->

<!--Breadcrumb-->
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<ol class="breadcrumb">
    <li></li>
</ol>
<!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
<!--End breadcrumb-->



<!--Page content-->
<!--===================================================-->
<div id="page-content">
    
    <div class="panel">
        <div class="panel-heading">
            <div class="panel-control">
                <a class="btn btn-info btn-sm pull-right btn-labeled fa fa-plus mar-top" id="nuevoRegistro" href="javascript:void(0);">Nuevo</a>
            </div>
            <h3 class="panel-title">Listado</h3>
        </div>
        <div class="panel-body">
            
            
            <div class="table-responsive">
                <table class="table table-striped table-bordered" id="tablaCampanas"  cellspacing="0" width="100%">
                    <thead>
                        <tr>
                            <th>CAMPAÑA</th>
                            <th>CLIENTE</th>
                            <th>ESTADO</th>
                            <th>FECHA</th>
                            <th>ACCIÓN</th>
                        </tr>
                    </thead>
                    <tbody>
                        
                    </tbody>
                </table>
            </div>


        </div><!--// fin ibox-content-->
    </div><!--// fin ibox-->

</div>
<!--===================================================-->
<!--End page content-->


<?php 
    echo $this->inlineScript()->prependFile($this->basePath('js/jquery.magnific-popup.min.js'))
                                ->prependFile($this->basePath('plugins/jquery-validation/additional-methods.min.js'))
                                ->prependFile($this->basePath('plugins/jquery-validation/jquery.validate.min.js'))

                                ->prependFile($this->basePath('plugins/dropzone/dropzone.min.js'))

                                ->prependFile($this->basePath('/plugins/colorpicker/bootstrap-colorpicker.min.js'))

                                ->prependFile($this->basePath('/plugins/bootstrap-select/ajax-bootstrap-select.min.js'))
                                ->prependFile($this->basePath('/plugins/bootstrap-select/bootstrap-select.min.js'));
?>

<link rel="stylesheet" href="<?php echo $this->basePath()?>/css/magnific-popup.css">

<!-- SELECT BOOTSTRAP -->
<link rel="stylesheet" href="<?php echo $this->basePath()?>/plugins/bootstrap-select/bootstrap-select.min.css">
<link rel="stylesheet" href="<?php echo $this->basePath()?>/plugins/bootstrap-select/ajax-bootstrap-select.min.css">

<!--Dropzone [ OPTIONAL ]-->
<link href="<?php echo $this->basePath(); ?>/plugins/dropzone/dropzone.css" rel="stylesheet">

<!-- +++++++++++++++++ -->
<!-- COLOR PICKER -->
<link href="<?php echo $this->basePath()?>/plugins/colorpicker/bootstrap-colorpicker.min.css" rel="stylesheet">


<script type="text/javascript">
    
    // *****************************************************
    //URL PROYECTOS
    var urlSaveIngCampanas          = '<?php echo $this->url("campanas/campanasIngresar"); ?>';
    var urlSaveEdiCampanas          = '<?php echo $this->url("campanas/campanasEditar"); ?>';
    var urlEliminarCampana          = '<?php echo $this->url("campanas/campanasEliminar"); ?>';
    var urlGetDataCampana           = '<?php echo $this->url("campanas/campanasGetData"); ?>';
    var urlChangeStatusCampana      = '<?php echo $this->url("campanas/campanasStatus"); ?>';
    var urlAutocompleteCampana      = '<?php echo $this->url("campanas/campanasAutorcomplete"); ?>';
    var urlTablaCampanas            = '<?php echo $this->url("campanas/campanasTabla"); ?>';
    var global_isLoadTablaCampanas  = false;

    // *****************************************************
    //URL cliente
    var urlAutocompleteCliente      ='<?php echo $this->url("clientes/clientesAutorcomplete"); ?>';


    var global_noImage              ='<?php echo $this->basePath()."/img/".$this->NoImage; ?>';

    var global_searchTable          = '<?php echo addslashes($this->search); ?>';
    var global_startTable           = '<?php echo $this->startTable; ?>';
    var global_lengthTable          = '<?php echo $this->lengthTable; ?>';
    var global_orderTable           = '<?php echo $this->orderTable; ?>';
    var global_orderDirTable        = '<?php echo ($this->order_dirTable==null)?"desc":$this->order_dirTable; ?>';

    // +++++++++++++++++++++++++++++++++++++++++++++++
    // LIMPIA EL FORMULARIO
    function clearForm()
    {
        document.getElementById("saveRegistro").reset();
        $("#campanaHidden").val("0");
        $(".imgCargando").empty();
    }

    function clearClassRow(tabla_name){
        $("#"+tabla_name+" tr").removeClass("danger");
        $("#"+tabla_name+" tr").removeClass("info");
    }

    function clearSelectBootstrap($selector){
        $selector.empty();
        $selector.selectpicker('refresh');
    }

    // +++++++++++++++++++++++++++++++++++++++++++
    // ENVIA LOS DATOS DE ING-EDIT
    function sendDataAjax(url, formData, cargando, $btn)
    {
        var source          = $("#alert-template").html();
        var template        = Handlebars.compile(source);
        var sourceCarg      = $("#imgCargando-template").html();
        var templateCarg    = Handlebars.compile(sourceCarg);
        var parent          = cargando.parents('.modal');
        $.ajax({
            url: url, 
            dataType: "json",
            type: 'POST',
            data: formData,
            cache: false,
            contentType: false,
            processData: false,
            beforeSend: function(){
                var contextCarg = { };
                cargando.html(templateCarg(contextCarg));
                $btn.button('loading');
            },
            success: function(data){
                $btn.button('reset');

                if(data.status=='ok'){

                    var context = {msj: data.msj, tipo: "alert-success" };
                    cargando.html(template(context));

                    setTimeout(function(){
                        $("#myModalCampana").modal('hide');
                    },900);

                    if(global_isLoadTablaCampanas==true){
                        $('#tablaCampanas').DataTable().draw(false);
                    }
                    
                }
                else{
                    var context = {msj: data.msj, tipo: "alert-danger" };
                    cargando.html(template(context));
                }
            },
            error: function(){
                $btn.button('reset');
                var context = {msj: "Ocurrio un error procesando los datos.", tipo: "alert-danger" };
                cargando.html(template(context));
            }
            
        });
    }

    function loadDataTablaCampanas(){
        
        if( global_isLoadTablaCampanas==true ){
            $('#tablaCampanas').DataTable().destroy();
        }

        $('#tablaCampanas').DataTable({
            "bProcessing": true,
            "bServerSide": true,
            "sAjaxSource": urlTablaCampanas,
            "columns": [
                { "data": "nombre" },
                { "data": "cliente" },
                { "data": "estado" },
                { "data": "fecha" },
                { "data": "version" }
            ],
            "columnDefs": [ { 
                        "targets": 4, 
                        "orderable": false 
            } ],
            // "order": [ 4, "desc" ],
            "iDisplayStart": parseInt(global_startTable),
            "iDisplayLength": parseInt(global_lengthTable),
            "oSearch": {"sSearch": global_searchTable},
            "order": [ parseInt(global_orderTable), global_orderDirTable ],
            responsive: true,
            "dom": 'T<"clear">lfrtip',
            "tableTools": {
                "sSwfPath": "<?php echo $this->basePath()?>/js/plugins/dataTables/swf/copy_csv_xls_pdf.swf"
            },
            "oLanguage": {
                "sProcessing":     "Procesando...",
                "sLengthMenu":     "Mostrar _MENU_ registros",
                "sZeroRecords":    "No se encontraron resultados",
                "sEmptyTable":     "Ningún dato disponible en esta tabla",
                "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                "sInfoPostFix":    "",
                "sSearch":         "Buscar:",
                "sUrl":            "",
                "sInfoThousands":  ",",
                "sLoadingRecords": "Cargando...",
                "oPaginate": {
                    "sFirst":    "Primero",
                    "sLast":     "Último",
                    "sNext":     "Siguiente",
                    "sPrevious": "Anterior",
                },
                "fnInfoCallback": null,
            },
            "fnDrawCallback": function( oSettings ) {
                // -------------------------------------------------
                // TOOLTIP DE LOS BOTONES
                $('[data-toggle="tooltip"]').tooltip({ html:true });

                $("img.lazy").lazyload({
                    effect: "fadeIn"
                });
            }
        });
        
    }


    function changeNameSlug(){
        var value = $.trim($(this).val());
        // value = value.replace(/ /g, "-");
        $("input[name='campaign_slug']").val(value.toLowerCase());
    }

    function initSelectBootstrap(url, $selector, datos){
        //========================================================================
        //CONFIGURACION AJAX SELECT
        var options = {
            ajax: {
                url     : url,
                type    : 'POST',
                dataType: 'json',
                // Use "{{{q}}}" as a placeholder and Ajax Bootstrap Select will
                // automatically replace it with the value of the search query.
                data    : datos
            },
            locale        : {
                emptyTitle: 'Ingrese texto para buscar...',
                searchPlaceholder:'Buscar...',
                preserveSelected: 'Selección actual',
                currentlySelected: 'Selección actual',
                errorText: 'No se encontrarón resultados',
                statusInitialized: '',
                statusNoResults: 'No se encontrarón resultados',
                statusSearching: 'Buscando...',
            },
            log           : 0,
            preprocessData: function (data) {
                var i, l = data.items.length, array = [];
                if (l) {
                    for (i = 0; i < l; i++) {
                        array.push($.extend(true, data.items[i], {
                            text : data.items[i].nombre,
                            value: data.items[i].id,
                        }));
                    }
                }
                // You must always return a valid array when processing data. The
                // data argument passed is a clone and cannot be modified directly.
                return array;
            }
        };

        $selector.selectpicker().filter('.with-ajax').ajaxSelectPicker(options);
        $selector.trigger('change');
        //========================================================================
    }

    $(document).ready(function(){


        var source          = $("#alert-template").html();
        var template        = Handlebars.compile(source);
        var sourceCarg      = $("#imgCargando-template").html();
        var templateCarg    = Handlebars.compile(sourceCarg);

        $('.alertaMSJ').delay(2500).slideToggle(2500);
        
        //=========================================================
        loadDataTablaCampanas();
        global_isLoadTablaCampanas=true;

        //=========================================================
        $('#bg_campaign_color').colorpicker();


        // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        // NUEVA
        $(document).on( "click", "#nuevoRegistro", function() {
            $("#saveRegistro").attr('action', urlSaveIngCampanas);
            $('#myModalCampana').modal({
                backdrop: 'static'
            });
            clearForm();
            $("#myModalCampana .modal-title").text("Nueva Campaña");
        });

        $('#myModalCampana').on('hide.bs.modal', function () {
            clearClassRow('tablaCampanas');
            clearForm();

            //habilitamos el campo slug y le agregamos el evento change (se lo quitamos al abrir modal en modo edicion)
            // $("input[name='campaign_title']").on('change',changeNameSlug);
            // $("input[name='campaign_slug']").prop('disabled', false);

            //LIMPIAMOS EL SELECTOR AJAX
            clearSelectBootstrap( $("#cliente") );

            $("#bg_campaign_color").colorpicker('setValue', '#000000' );
        });

        //=========================================================
        // FORMATEA EL NOMBRE Y LOS PONE EN EL INPUT SLUG
        // UTILIZA LA FUNCION "CHANGENAMESLUG" PARA REALIZAR ESTO
        // $("input[name='campaign_title']").on('change',changeNameSlug);
        //===============================================
        // $("input[name='campaign_slug']").change(function () {
        
        //     var value = $.trim($(this).val());
        //     value = value.replace(/ /g, "-");
        //     $("input[name='campaign_slug']").val(value.toLowerCase());
        // });
        // -- FIN FORMATEA titulo


        var datos_select={
            search: '{{{q}}}'
        };
        initSelectBootstrap(urlAutocompleteCliente , $("#cliente"), datos_select);


        // ++++++++++++++++++++++++++++++++++++++++++++++
        // INGRESA 
        var optionRules={
        };
        var messagesRules={
            campaign_title: {
                required: "Este campo es requerido.",
                maxlength:"Debe ingresar menos de {0} caracteres."
            },
            // campaign_slug: {
            //     required: "Este campo es requerido.",
            //     maxlength:"Debe ingresar menos de {0} caracteres."
            // },
            campaign_color: {
                required: "Este campo es requerido.",
                maxlength:"Debe ingresar menos de {0} caracteres."
            }
        };
        $("#saveRegistro").validate({
            option:optionRules,
            messages:messagesRules,
            errorPlacement: function(error, element) {
                $(element).closest('.form-group').append(error);
            },
            highlight: function(element, errorClass){ 
                $(element).closest('.form-group').addClass('has-error');
            },
            unhighlight: function(element, errorClass){ 
                $(element).closest('.form-group').removeClass('has-error');
            },
            submitHandler: function(form){

                var formData = new FormData( $("#saveRegistro")[0] );
                sendDataAjax( $("#saveRegistro").attr("action") , formData, $("#myModalCampana .imgCargando"), $("#myModalCampana .btnSave"));
            }
        });

        // ++++++++++++++++++++++++++++++++++++++++++++++++++++++++
        // LOAD DATOS PARA EDITAR REGION
        $( "#tablaCampanas" ).on( "click", ".linkEditar", function() {
            
            clearForm();
            var data=$(this).attr('data');
            $("#tablaCampanas #row_"+data).addClass("info");

            $("#saveRegistro").attr('action', urlSaveEdiCampanas);
            $('#myModalCampana').modal({
                backdrop: 'static'
            });
            // +++++++++++++++++++++++++++++++++++++
            $("#myModalCampana .modal-title").text("Editar Campaña");

            // ++++++++++++++++++++++++++++++++++++++
            // MENSAJE CARGANDO
            $("#myModalCampana .imgCargando").html(templateCarg( {} ));

            //deshabilitamos el campo slug y le quitamos el evento change (se lo volvemos a agregar al cerrar modal)
            // $("input[name='campaign_slug']").prop('disabled', true);
            // $("input[name='campaign_title']").off('change',changeNameSlug);
            

            // ----------------------------------------------
            // ENVIA PETICION
            $.post( urlGetDataCampana, { campana: data }, function( data ) {

                $("#myModalCampana .imgCargando").empty();
                if (data.status=="ok") {
                    
                    $("#campaign_title").val( data.campaign_title );
                    // $("#campaign_slug").val( data.campaign_slug );

                    $("#campaign_color").val( data.campaign_color );
                    $("#bg_campaign_color").colorpicker('setValue', data.campaign_color );

                    //AGREGAMOS EL cliente
                    if(data.cliente.id>0){
                        $("#cliente").html('<option value="'+data.cliente.id+'">'+data.cliente.name+'</option>');
                        $('#cliente').selectpicker('refresh');
                    }else{
                        clearSelectBootstrap( $('#cliente') );
                    }
                    
                    $("#campanaHidden").val( data.id );

                }else{
                    var context = {msj: data.msj, tipo: "alert-danger" };
                    $("#myModalCampana .imgCargando").html(template(context));
                }

            }, "json").fail(function(){
                console.log('Error en el servidor');
                $("#myModalCampana .imgCargando").empty();
            });
        });

        
        //========================================================================
        //ELIMINA
        $('#tablaCampanas').on('click', '.linkEliminar',function () {
            var id=$(this).attr('data');
            $("#tablaCampanas #row_"+id).addClass("danger");
            swal({
                title: "¿Eliminar?",
                text: "Estas seguro de eliminar esta campaña?",
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: "#DD6B55",
                confirmButtonText: "Si, Eliminar",
                cancelButtonText: "Cancelar",
                closeOnConfirm: false,
                showLoaderOnConfirm: true,
            }, function (isConfirm) {
                if (isConfirm) {
                    $.post( urlEliminarCampana, { campana: id }, function( data ) {
                        if (data.status=="ok") {

                            swal("Eliminado!", data.msj, "success");
                            setTimeout(function(){
                                $('#tablaCampanas').DataTable().draw(false);
                            }, 700);
                            clearClassRow('tablaCampanas');
                        }
                        else{
                            swal("Error", data.msj, "error");
                            clearClassRow('tablaCampanas');
                        }
                        
                    }, "json").fail(function(){
                        clearClassRow('tablaCampanas');
                        console.log('Error en el server');
                        swal("Error", 'Error en el servidor (contacte a su administrador).', "error");
                    });
                }
                else{
                    clearClassRow('tablaCampanas');
                }
                
            });
        });
        
        //========================================================================
        //deshabilita - habilita
        $('#tablaCampanas').on('click', '.linkStatus',function () {
            var id=$(this).attr('data');
            $("#tablaCampanas #row_"+id).addClass("danger");

            var text="Estas seguro de deshabilitar esta campaña?";
            var confirmButtonText="Si, Deshabilitar";
            var confirmButtonColor="#DD6B55";
            var title='¿Deshabilitar?';
            var titleExito="Deshabilitada!";
            if($(this).attr('data-status')=='deshabilitado'){
                text="Estas seguro de habilitar esta campaña?";
                confirmButtonText="Si, Habilitar";
                confirmButtonColor="#1ab394";
                title='¿Habilitar?';
                titleExito="Habilitada!";
            }
            swal({
                title: title,
                text: text,
                type: "warning",
                showCancelButton: true,
                confirmButtonColor: confirmButtonColor,
                confirmButtonText: confirmButtonText,
                cancelButtonText: "Cancelar",
                closeOnConfirm: false,
                showLoaderOnConfirm: true,
            }, function (isConfirm) {
                if (isConfirm) {
                    $.post( urlChangeStatusCampana, { campana: id }, function( data ) {
                        if (data.status=="ok") {

                            swal(titleExito, data.msj, "success");
                            setTimeout(function(){
                                $('#tablaCampanas').DataTable().draw(false);
                            }, 700);
                            clearClassRow('tablaCampanas');
                        }
                        else{
                            swal("Error", data.msj, "error");
                        }
                        

                    }, "json").fail(function(){
                        console.log('Error en el server');
                        swal("Error", 'Error en el servidor (contacte a su administrador).', "error");
                    });
                }else{
                    clearClassRow('tablaCampanas');
                }
                
            });
        });
        

    });

</script>


<!-- MODAL CAMPAÑA -->
<div id="myModalCampana" class="modal inmodal fade" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content" >
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title"></h4>
            </div>

            <!-- ICON CARGANDO -->
            <div class="panel-alert">
                <div class="imgCargando" class="alert-wrap in"></div>
            </div>
            <!-- /.FIN ICON CARGANDO -->
            
            <form id="saveRegistro" action="" method="POST" enctype="multipart/form-data">

                <div class="modal-body" >
                    
                    <div class="row">
                        <div class="col-lg-12 col-md-12">

                            <br />
                            <div class="form-group">
                                <label for="campaign_title" class="text-semibold">Campaña *</label>
                                <input type="text" class="form-control" name="campaign_title" id="campaign_title" maxlength="200" required />
                            </div>

                            <!-- <div class="form-group">
                                <label for="campaign_slug" class="text-semibold">Slug *</label>
                                <input type="text" class="form-control" name="campaign_slug" id="campaign_slug" maxlength="200" required />
                            </div> -->

                            <div class="form-group">
                                <label for="" class="text-semibold">Color Distintivo *</label> <em>(Le será mas facil reconocer las menciones dentro del calendario)</em>
                                <div id="bg_campaign_color" class="input-group colorpicker-component">
                                    <input type="text" name="campaign_color" id="campaign_color" value="" class="form-control" required maxlength="7" />
                                    <span class="input-group-addon"><i></i></span>
                                </div>

                            </div>

                            <div class="form-group">
                                <label for="cliente" class="text-semibold">Cliente *</label>
                                <select required name="cliente" id="cliente" class="form-control with-ajax" data-live-search="true">
                                </select>
                            </div>

                                    
                            <input type="hidden" value="0" id="campanaHidden" name="campanaHidden" />
                            <br />
                        </div>
                    </div>
                </div>
                
                <div class="modal-footer">
                    <button type="button" class="btn btn-default btn-sm" data-dismiss="modal" >Cerrar</button>
                    <button 
                        class="btn btn-primary btn-sm btnSave" 
                        data-loading-text="<i class='fa fa-spinner fa-pulse fa-fw'></i> Guardando">
                        <i class="fa fa-floppy-o"></i> Guardar
                    </button>
                </div>
            </form>

        </div>
    </div>
</div>

